# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.CharField(max_length=100)),
                ('kes', models.FloatField()),
                ('usd', models.FloatField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
