# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinprice',
            name='time_added',
            field=models.DateTimeField(),
        ),
    ]
